### ISSUE TITLE
NoBrokersAvailable in kafka-idmef-converter

### ISSUE THREAD

**Issue by agil3b3ast** [scissor-project/open-scissor#53]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced after disabling all Vagrant plugins you installed
    * Checked that your issue isn't already filed: https://github.com/scissor-project/open-scissor/issues

### Description
 NoBrokersAvailable in kafka-idmef-converter. It seems that kafka-idmef-converter cannot connect to kafka server.  

### Host Environment
- Host operating system and version: Windows 10
- Vagrant version: 2.0.1
- Hypervisor version: VirtualBox 5.2.2

### Output
This is the output of `sudo converter`
```
Using configuration file : /etc/converter.conf
Connecting to kafka 10.10.1.55:9092
Reading from topics ['cam', 'env', 'net', 'scada']
Writing to topic IDMEF
Traceback (most recent call last):
  File "/bin/converter", line 11, in <module>
    load_entry_point('kafka-idmef-converter==0.2.4', 'console_scripts', 'converter')()
  File "/usr/lib/python2.7/site-packages/converter/__main__.py", line 29, in main
    converter.Converter(conf["kafka_server"], conf["kafka_port"], conf["consumer_topics"], conf["producer_topic"], conf["block_filters"]).run()
  File "/usr/lib/python2.7/site-packages/converter/converter.py", line 139, in __init__
    self.kafka_consumer = self.build_kafka_consumer()
  File "/usr/lib/python2.7/site-packages/converter/converter.py", line 144, in build_kafka_consumer
    kafka_consumer = kafka.KafkaConsumer(bootstrap_servers="%s:%s" % (self.kafka_server, self.kafka_port))
  File "/usr/lib/python2.7/site-packages/kafka/consumer/group.py", line 324, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/usr/lib/python2.7/site-packages/kafka/client_async.py", line 221, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/usr/lib/python2.7/site-packages/kafka/client_async.py", line 826, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
```

### Steps to Reproduce

1. `vagrant up gateway`
2. `vagrant up kafka`
3. `vagrant up kafka-idmef-converter`
4. `sudo converter`

**Expected behavior:** kafka-idmef-converter service success

**Actual behavior:** kafka-idmef-converter service fails

**Reproduces how often:** Always

#### Additional Information

Kafka server seems to be running. It seems that is not an iptables issue.

### References

N/A

**Comment by ferrarimarco** [comment]
Can you please check if:
1. (`netstat` on `kafka` VM) if the 9092 port is open and listening
1. you can ping `10.10.1.55` from `kafka-idmef-converter`
1. `10.10.1.55` is in fact the IP of one of `kafka` VM interfaces
1. (`nmap` on `kafka-idmef-converter` VM) if `9092` is open on `10.10.1.55`

Thanks

**Comment by agil3b3ast** [comment]
@ferrarimarco I was wrong. It should be an iptables issue, again.

**Comment by agil3b3ast** [comment]
@ferrarimarco if you can please follow the steps below:

- switch to _fix/GH-53-kafka-nobroker_
- `vagrant up gateway`
- `vagrant up kafka`
- `vargrant up kafka-idmef-converter`
- `vagrant ssh kafka-idmef-converter`
- `systemctl status converter`
