### ISSUE TITLE
logstash24 deployment script: IP address parameter is set to the hostname

### ISSUE THREAD

**Issue by StefanoSalsano** [scissor-project/open-scissor#59]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced after disabling all Vagrant plugins you installed
    * Checked that your issue isn't already filed: https://github.com/scissor-project/open-scissor/issues

### Description

running "vagrant up" after a clone of master branch results in an error in logstash24

### Host Environment
- Host operating system and version: windows 10
- Vagrant version: Vagrant 2.0.1
- Hypervisor version: Version 5.2.8 r121009 (Qt5.6.2)

### Output

[vagrant-error.log](https://github.com/scissor-project/open-scissor/files/1846802/vagrant-error.log)

### Steps to Reproduce

1. clone the repository
2. vagrant up

**Comment by ferrarimarco** [comment]
A quicker way to reproduce is `vagrant up gateway logstash24`

**Comment by ferrarimarco** [comment]
@StefanoSalsano fixed, thanks for reporting
