### ISSUE TITLE
Install dependencies script assumes too much

### ISSUE THREAD

**Issue by ferrarimarco** [scissor-project/open-scissor#66]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/scissor-project/open-scissor/issues

### Description

The `install-dependencies.sh` has multiple issues:
1. Assumes you are on a Debian-like system (installs packages with APT)
1. Assumes you already have a working Ruby environment with bundler

**Comment by Davidepad** [comment]
@ferrarimarco I use this file to set up my Vagrant Ubuntu machine that I use for my tests

I left it inside the branch for convenience.

I have to create another branch to make other changes and I would have removed it.

But if it creates problems it can easily be removed.

It only serves in development.

**Comment by ferrarimarco** [comment]
Can you try the development box included in this project? I ironed out a couple of bugs in the last release so it should be fully operational.

In any case I'll remove the script if it's not needed. Thanks!
